In [1]:
import numpy as np

In [2]:
from sklearn.metrics.pairwise import euclidean_distances

In [3]:
positions = np.arange(10).reshape(-1,2)

In [4]:
positions

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
dist_matrix = euclidean_distances(positions)
dist_matrix

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425],
       [ 8.48528137,  5.65685425,  2.82842712,  0.        ,  2.82842712],
       [11.3137085 ,  8.48528137,  5.65685425,  2.82842712,  0.        ]])

In [6]:
dist_matrix[dist_matrix<5] = 0

In [7]:
dist_matrix

array([[ 0.        ,  0.        ,  5.65685425,  8.48528137, 11.3137085 ],
       [ 0.        ,  0.        ,  0.        ,  5.65685425,  8.48528137],
       [ 5.65685425,  0.        ,  0.        ,  0.        ,  5.65685425],
       [ 8.48528137,  5.65685425,  0.        ,  0.        ,  0.        ],
       [11.3137085 ,  8.48528137,  5.65685425,  0.        ,  0.        ]])

In [8]:
import tensorflow as tf

In [9]:
tf.__version__

'1.9.0'

In [10]:
from tf.keras.layers import 

<module 'tensorflow.keras.layers' from '/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow/keras/layers/__init__.py'>