In [1]:
import tensorflow as tf

In [9]:
import numpy as np

In [2]:
tf.__version__

'2.2.0'

In [3]:
tf.executing_eagerly()

True

In [23]:
y_true = np.zeros(30).reshape(2,5,3)
y_pred = np.ones(30).reshape(2,5,3)
mask = np.zeros(10).reshape(2,5)
mask[1,1]=0

In [24]:
y_true

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
y_pred

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
h = tf.keras.losses.Huber(reduction=tf.keras.losses.Reduction.NONE)
h(y_pred, y_true,).numpy()

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]], dtype=float32)

In [7]:
a = (1,2,3)
b = (2)

In [8]:
b[0]

TypeError: 'int' object is not subscriptable

In [12]:
y_true = np.arange(30).reshape(2,5,3)
y_pred = np.ones(30).reshape(2,5,3)

In [13]:
y_true

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [35]:
inds = np.expand_dims(y_true.argmax(-1),axis=2)

np.take_along_axis(y_true,inds,axis=-1)

array([[[ 2],
        [ 5],
        [ 8],
        [11],
        [14]],

       [[17],
        [20],
        [23],
        [26],
        [29]]])

In [36]:
inds = np.expand_dims(y_true.argmax(-1),axis=2)
np.squeeze(np.take_along_axis(y_true,inds,axis=-1),axis=2)

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [41]:
np.zeros(5).astype(bool).all()

False

In [49]:
import tensorflow.python.keras.callbacks as kkk