In [1]:
import tensorflow as tf

In [5]:
import numpy as np

In [2]:
tf.__version__

'2.2.0'

In [3]:
tf.executing_eagerly()

True

In [23]:
y_true = np.zeros(30).reshape(2,5,3)
y_pred = np.ones(30).reshape(2,5,3)
mask = np.zeros(10).reshape(2,5)
mask[1,1]=0

In [24]:
y_true

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
y_pred

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
h = tf.keras.losses.Huber(reduction=tf.keras.losses.Reduction.NONE)
h(y_pred, y_true,).numpy()

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]], dtype=float32)